ALTER TABLE conversations
  ADD COLUMN IF NOT EXISTS muted    BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS pinned   BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS unread   BOOLEAN DEFAULT FALSE;
